package tugas.besar.pbo;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Koneksi.KoneksiDB;
import java.util.logging.Logger;

/**
 *
 * @author _ A S U S _
 */
public class pegawai extends javax.swing.JFrame {

    public pegawai() {
        initComponents();
        this.setLocationRelativeTo(null);
        init();
        tampildata();
    }
    private void init(){
        txt_nip_pegawai.setText("");
        txt_nama_pegawai.setText("");
        txt_notelp_pegawai.setText("");
        txt_alamat_pegawai.setText("");
        
        cmb_jenkel_pegawai.removeAllItems();
        cmb_jenkel_pegawai.addItem("Laki-laki");
        cmb_jenkel_pegawai.addItem("Perempuan");
    }
    private void tampildata(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NIP ");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Nomor Telp");
        model.addColumn("Alamat");
        tbl_pegawai.setModel(model);
        try {            
            String sql = "SELECT * FROM pegawai";
            java.sql.Connection conn=(Connection)Koneksi.KoneksiDB.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while (res.next()) {                
                Object[] obj = new Object[5];
                obj[0] = res.getString("nip_pegawai"); 
                obj[1] = res.getString("nama_pegawai");
                obj[2] = res.getString("jenkel_pegawai");
                obj[3] = res.getString("notelp_pegawai");
                obj[4] = res.getString("alamat_pegawai");

                model.addRow(obj);
            }
            tbl_pegawai.setModel(model);
            //s.close();
            stm.close();
        } catch (SQLException ex) {
            Logger.getLogger(pegawai.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_reset = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        txt_nama_pegawai = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_hapus = new javax.swing.JButton();
        nama1 = new javax.swing.JLabel();
        nama2 = new javax.swing.JLabel();
        txt_alamat_pegawai = new javax.swing.JTextField();
        nama3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_pegawai = new javax.swing.JTable();
        txt_nip_pegawai = new javax.swing.JTextField();
        nama4 = new javax.swing.JLabel();
        txt_notelp_pegawai = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        cmb_jenkel_pegawai = new javax.swing.JComboBox<>();
        btn_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 264, 94, -1));

        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        getContentPane().add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 264, 94, -1));
        getContentPane().add(txt_nama_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 106, 197, 32));

        nama.setBackground(new java.awt.Color(255, 255, 255));
        nama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nama.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama.setText("Jenis Kelamin");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 144, -1, 32));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setForeground(new java.awt.Color(204, 153, 255));

        jLabel1.setBackground(new java.awt.Color(51, 0, 255));
        jLabel1.setFont(new java.awt.Font("Book Antiqua", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Pegawai");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jLabel1)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 687, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 264, 94, -1));

        nama1.setBackground(new java.awt.Color(255, 255, 255));
        nama1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nama1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama1.setText("NIP Pegawai");
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 67, -1, 32));

        nama2.setBackground(new java.awt.Color(255, 255, 255));
        nama2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nama2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama2.setText("Nama Pegawai");
        getContentPane().add(nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 100, -1, 32));
        getContentPane().add(txt_alamat_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 226, 197, 32));

        nama3.setBackground(new java.awt.Color(255, 255, 255));
        nama3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nama3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama3.setText("Nomor Telp");
        getContentPane().add(nama3, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 182, 92, 32));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        tbl_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pegawaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_pegawai);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 315, -1, 111));
        getContentPane().add(txt_nip_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 68, 197, 32));

        nama4.setBackground(new java.awt.Color(255, 255, 255));
        nama4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nama4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nama4.setText("Alamat");
        getContentPane().add(nama4, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 226, 150, 32));
        getContentPane().add(txt_notelp_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 183, 198, 32));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 264, 94, -1));

        cmb_jenkel_pegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmb_jenkel_pegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 144, 197, 32));

        btn_menu.setText("Menu Utama");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        getContentPane().add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 67, 102, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        resetdata();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            String sql ="UPDATE pegawai SET nama_pegawai = '"+txt_nama_pegawai.getText()+"', "
             + "jenkel_pegawai = '"+cmb_jenkel_pegawai.getSelectedItem()+"',"
             + "notelp_pegawai= '"+txt_notelp_pegawai.getText()+"',"
            + "alamat_pegawai= '"+txt_alamat_pegawai.getText()+"' WHERE nip_pegawai = '"+txt_nip_pegawai.getText()+"'";
            System.out.println(sql);
            java.sql.Connection conn=(Connection)KoneksiDB.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil di edit");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        tampildata();
        resetdata();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        try {
            String sql ="DELETE FROM pegawai WHERE nip_pegawai='"+txt_nip_pegawai.getText()+"'";
            java.sql.Connection conn=(Connection)KoneksiDB.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Berhasil di hapus");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampildata();
        resetdata();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void tbl_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pegawaiMouseClicked
        int baris = tbl_pegawai.rowAtPoint(evt.getPoint());
        String kode_buku =tbl_pegawai.getValueAt(baris, 0).toString();
        txt_nip_pegawai.setText(kode_buku);
        String judul_buku = tbl_pegawai.getValueAt(baris,1).toString();
        txt_nama_pegawai.setText(judul_buku);
        String jenkel_pegawai = tbl_pegawai.getValueAt(baris, 2).toString();
        cmb_jenkel_pegawai.setSelectedItem(jenkel_pegawai);
        String notelp_pegawai=tbl_pegawai.getValueAt(baris, 3).toString();
        txt_notelp_pegawai.setText(notelp_pegawai);
        String alamat_pegawai=tbl_pegawai.getValueAt(baris, 4).toString();
        txt_alamat_pegawai.setText(alamat_pegawai);
    }//GEN-LAST:event_tbl_pegawaiMouseClicked

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        try {
            String sql = "INSERT INTO pegawai (nip_pegawai,nama_pegawai,jenkel_pegawai,notelp_pegawai,alamat_pegawai) VALUES "
            + "('"+txt_nip_pegawai.getText()+"',"
            + "'"+txt_nama_pegawai.getText()+"',"
            + "'"+cmb_jenkel_pegawai.getSelectedItem()+"',"
            + "'"+txt_notelp_pegawai.getText()+"',"
            + "'"+txt_alamat_pegawai.getText()+"')";
            java.sql.Connection conn=(Connection)KoneksiDB.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
            tampildata();
            resetdata();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        formmenu a = new formmenu();
        a.setVisible(true);
        this.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_btn_menuActionPerformed
    private void resetdata(){
        txt_nip_pegawai.setText(null);
        txt_nama_pegawai.setText(null);
        cmb_jenkel_pegawai.setSelectedItem(this);
        txt_notelp_pegawai.setText(null);
        txt_alamat_pegawai.setText(null);  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cmb_jenkel_pegawai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nama2;
    private javax.swing.JLabel nama3;
    private javax.swing.JLabel nama4;
    private javax.swing.JTable tbl_pegawai;
    private javax.swing.JTextField txt_alamat_pegawai;
    private javax.swing.JTextField txt_nama_pegawai;
    private javax.swing.JTextField txt_nip_pegawai;
    private javax.swing.JTextField txt_notelp_pegawai;
    // End of variables declaration//GEN-END:variables
}
